name: Compare APK
on:
  pull_request:
    branches: [ master ]
jobs:
  build-master:
    name: Build master Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: master
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.9'
          channel: 'stable'
      - run: flutter pub get
      - run: |
            flutter build apk --debug
            mv build/app/outputs/apk/debug/app-debug.apk build/app/outputs/apk/debug/app-master.apk
      - name: Upload master APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: build/app/outputs/apk/debug/app-master.apk
  build-pr:
    name: Build PR Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.9'
          channel: 'stable'
      - run: flutter pub get
      - run: |
            flutter build apk --debug
            mv build/app/outputs/apk/debug/app-debug.apk build/app/outputs/apk/debug/app-pr.apk
      - name: Upload pr APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: build/app/outputs/apk/debug/app-pr.apk
  # Execute Diffuse only when the two APKs are built successfully
  diffuse:
    needs: [build-master, build-pr]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download APKs
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Change diffuse permissions
        run: chmod +x ./diffuse
      - name: Execute Diffuse
        run: ./diffuse diff apk/app-master.apk apk/app-pr.apk
